In [1]:
import pandas as pd
import numpy as np

In [11]:
url="C:/Users/user/Desktop/Data.xlsx"
df=pd.read_excel(url)

# logistique regression

In [12]:
df

Date  Day  Course  Nature  Number_I  Number_D   Age  Season  \
0   2019-03-01  Fri     1.0       1         1         0  36.0       1   
1   2018-11-10  Sat     0.0       2         7         3  44.0       0   
2   2019-03-11  Mon     0.0       3         1         2  45.0       0   
3   2018-07-12  Thu     1.0       2         1         1  35.0       0   
4   2019-01-13  Sun     1.0       2         1         0  34.0       0   
..         ...  ...     ...     ...       ...       ...   ...     ...   
428 2020-07-04  Sat     0.0       2         3         1  34.0       0   
429 2020-05-07  Thu     1.0       2         6         0  35.0       0   
430 2020-08-08  Sat     NaN       1         0         0  28.0       0   
431 2018-02-09  Fri     NaN       2         6         1  36.0       0   
432 2018-12-09  Sun     NaN       2         1         0  37.0       0   

     License  Speed  ...  Sex  Education    Vehicle Road_surface  \
0          0      1  ...    1          4  Motocycle            1   
1          0      1  ...    1          2        Car            1   
2          0      0  ...    2          2        Car            1   
3          0      0  ...    1          2        Car            1   
4          0      1  ...    1          2        Car            1   
..       ...    ...  ...  ...        ...        ...          ...   
428        0      1  ...    1          2        Car            1   
429        0      1  ...    2          2        Car            1   
430        0      0  ...    1          2      Truck            2   
431        0      0  ...    1          2      Truck            1   
432        0      0  ...    1          2      Truck            2   

     Visibility_Cat  Visibility  Visibilityclass     Cause Cause_Cat Accident  
0                 3         258         Far view  Inattent     Human        1  
1                 3         300         Far view  Inattent     Human        1  
2                 3         233         Far view  Pour ove     Human        1  
3                 3         300         Far view  Excessiv     Human        1  
4                 2         200     Average view  Excessiv     Human        1  
..              ...         ...              ...       ...       ...      ...  
428               3         215         Far view  Excessiv     Human        1  
429               2         200     Average view  Excessiv     Human        1  
430               3         240         Far view  Light Da     Human        0  
431               2         150     Average view  Excessiv     Human        1  
432               2         200     Average view  Drowsine     Human        1  

[433 rows x 21 columns]

In [13]:
df.isna().sum()

Date               0
Day                0
Course             3
Nature             0
Number_I           0
Number_D           0
Age                1
Season             0
License            0
Speed              0
Experience         0
Sex                0
Education          0
Vehicle            0
Road_surface       0
Visibility_Cat     0
Visibility         0
Visibilityclass    0
Cause              0
Cause_Cat          0
Accident           0
dtype: int64

In [14]:
df=df.dropna()

In [15]:
df.isna().sum()

Date               0
Day                0
Course             0
Nature             0
Number_I           0
Number_D           0
Age                0
Season             0
License            0
Speed              0
Experience         0
Sex                0
Education          0
Vehicle            0
Road_surface       0
Visibility_Cat     0
Visibility         0
Visibilityclass    0
Cause              0
Cause_Cat          0
Accident           0
dtype: int64

In [16]:
df=df.drop(columns='Date')
df=df.drop(columns='Visibilityclass')

In [17]:
df['Age'] = df['Age'].astype(int)
df['Course'] = df['Course'].astype(int)

In [18]:
df['Day'] = df['Day'].astype('category')
df['Day'] = df['Day'].cat.codes

df['Vehicle'] = df['Vehicle'].astype('category')
df['Vehicle'] = df['Vehicle'].cat.codes

df['Cause'] = df['Cause'].astype('category')
df['Cause'] = df['Cause'].cat.codes

df['Cause_Cat'] = df['Cause_Cat'].astype('category')
df['Cause_Cat'] = df['Cause_Cat'].cat.codes


In [19]:
df

Day  Course  Nature  Number_I  Number_D  Age  Season  License  Speed  \
0      0       1       1         1         0   36       1        0      1   
1      2       0       2         7         3   44       0        0      1   
2      1       0       3         1         2   45       0        0      0   
3      4       1       2         1         1   35       0        0      0   
4      3       1       2         1         0   34       0        0      1   
..   ...     ...     ...       ...       ...  ...     ...      ...    ...   
425    3       0       3         3         1   55       1        0      1   
426    4       0       4         2         0   37       1        1      0   
427    0       1       2         1         0   56       1        0      1   
428    2       0       2         3         1   34       0        0      1   
429    4       1       2         6         0   35       0        0      1   

     Experience  Sex  Education  Vehicle  Road_surface  Visibility_Cat  \
0             1    1          4        2             1               3   
1             4    1          2        1             1               3   
2             1    2          2        1             1               3   
3             3    1          2        1             1               3   
4             2    1          2        1             1               2   
..          ...  ...        ...      ...           ...             ...   
425           2    1          2        3             1               3   
426           2    1          2        1             1               3   
427           2    1          3        2             1               1   
428           4    1          2        1             1               3   
429           2    2          2        1             1               2   

     Visibility  Cause  Cause_Cat  Accident  
0           258      5          2         1  
1           300      5          2         1  
2           233     12          2         1  
3           300      2          2         1  
4           200      2          2         1  
..          ...    ...        ...       ...  
425         300      2          2         1  
426         234     14          2         1  
427         100      5          2         1  
428         215      2          2         1  
429         200      2          2         1  

[429 rows x 19 columns]

In [20]:
X=df.drop(columns='Accident')
X

Day  Course  Nature  Number_I  Number_D  Age  Season  License  Speed  \
0      0       1       1         1         0   36       1        0      1   
1      2       0       2         7         3   44       0        0      1   
2      1       0       3         1         2   45       0        0      0   
3      4       1       2         1         1   35       0        0      0   
4      3       1       2         1         0   34       0        0      1   
..   ...     ...     ...       ...       ...  ...     ...      ...    ...   
425    3       0       3         3         1   55       1        0      1   
426    4       0       4         2         0   37       1        1      0   
427    0       1       2         1         0   56       1        0      1   
428    2       0       2         3         1   34       0        0      1   
429    4       1       2         6         0   35       0        0      1   

     Experience  Sex  Education  Vehicle  Road_surface  Visibility_Cat  \
0             1    1          4        2             1               3   
1             4    1          2        1             1               3   
2             1    2          2        1             1               3   
3             3    1          2        1             1               3   
4             2    1          2        1             1               2   
..          ...  ...        ...      ...           ...             ...   
425           2    1          2        3             1               3   
426           2    1          2        1             1               3   
427           2    1          3        2             1               1   
428           4    1          2        1             1               3   
429           2    2          2        1             1               2   

     Visibility  Cause  Cause_Cat  
0           258      5          2  
1           300      5          2  
2           233     12          2  
3           300      2          2  
4           200      2          2  
..          ...    ...        ...  
425         300      2          2  
426         234     14          2  
427         100      5          2  
428         215      2          2  
429         200      2          2  

[429 rows x 18 columns]

In [87]:
y=df["Accident"]
y

0      1
1      1
2      1
3      1
4      1
      ..
425    1
426    1
427    1
428    1
429    1
Name: Accident, Length: 429, dtype: int64

In [114]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=21)

In [115]:
x_train.sample(5)

Day  Course  Nature  Number_I  Number_D  Age  Season  License  Speed  \
89     1       1       3         0         1   27       0        0      1   
307    0       1       2         0         0   53       1        0      1   
188    4       0       3         5         0   65       0        0      0   
160    6       0       4         0         1   34       0        1      1   
393    0       1       2         1         0   54       1        0      0   

     Experience  Sex  Education  Vehicle  Road_surface  Visibility_Cat  \
89            3    1          2        1             1               1   
307           4    1          1        1             1               3   
188           4    1          2        3             1               3   
160           4    1          2        1             2               2   
393           1    1          3        1             1               2   

     Visibility  Cause  Cause_Cat  
89          100      2          2  
307         248      1          2  
188         300      2          2  
160         130      1          2  
393         200      9          2

In [116]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [117]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [118]:
x_test_scaled

array([[-1.08513505,  1.33198857, -0.55982637, ...,  1.32730763,
        -0.20824968,  0.41281255],
       [-0.07076968, -0.75075719, -1.54237876, ...,  0.32235329,
         0.48057618, -1.06643242],
       [ 0.43641301, -0.75075719,  1.40527843, ...,  1.47087253,
         1.39901066,  0.41281255],
       ...,
       [ 1.45077839, -0.75075719, -1.54237876, ...,  0.32235329,
        -0.89707554,  0.41281255],
       [-1.59231774,  1.33198857,  0.42272603, ...,  0.25057084,
        -0.20824968,  0.41281255],
       [-0.57795237,  1.33198857, -0.55982637, ...,  0.25057084,
         0.02135894,  0.41281255]])

In [119]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(random_state=0,
                            C=1,
                            fit_intercept=True).fit(x_train_scaled,y_train)

In [120]:
log_reg.predict(x_test_scaled)  #compare avec np.array(y_test)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
      dtype=int64)

In [121]:
np.array(y_test)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
      dtype=int64)

In [122]:
log_reg.score(x_test_scaled,y_test)  #score is 0.9883720930232558

0.9883720930232558

In [129]:
#independant test

Day=int(input("the Day"))
Course=int(input("the Course"))
Nature=int(input("the Nature"))
Number_I=int(input("the Number_I"))
Number_D=int(input("the Number_D"))
Age=int(input("the Age"))
Season=int(input("the Season"))
License=int(input("the License"))
Speed=int(input("the Speed"))
Experience=int(input("the Experience"))
Sex=int(input("the Sex"))
Education=int(input("the Education"))
Vehicle=int(input("the Vehicle"))
Road_surface=int(input("the Road_surface"))
Visibility_Cat=int(input("the Visibility_Cat"))
Visibility=int(input("the Visibility"))
Cause=int(input("the Cause"))
Cause_Cat=int(input("the Cause_Cat"))





persone ={'Day':[Day],
          'Course':[Course],
          'Nature':[Nature],
          'Number_I':[Number_I],
          'Number_D':[Number_D],
          'Age':[Age],
          'Season':[Season],
          'License':[License],
          'Speed':[Speed],
          'Experience':[Experience],
          'Sex':[Sex],
          'Education':[Education],
          'Vehicle':[Vehicle],
          'Road_surface':[Road_surface],
          'Visibility_Cat':[Visibility_Cat],
          'Visibility':[Visibility],
          'Cause':[Cause],
          'Cause_Cat':[Cause_Cat],
}
persone=pd.DataFrame(persone)
persone = scaler.fit_transform(persone)
pr=log_reg.predict(persone)
if pr[0]==1:
    print("This person will have the accident ")
else:
    print("This person will not have an accident.")

the Day0
the Course1
the Nature2
the Number_I0
the Number_D1
the Age0
the Season2
the License1
the Speed0
the Experience2
the Sex1
the Education2
the Vehicle1
the Road_surface1
the Visibility_Cat120
the Visibility12
the Cause2
the Cause_Cat2
This person will have the accident 


# analyse discriminatoire

In [123]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

adl = LinearDiscriminantAnalysis(solver='svd')

adl.fit(X=x_train_scaled,y=y_train)

LinearDiscriminantAnalysis()

In [124]:
print(adl.coef_)

[[-0.00595709 -0.02501874 -0.11980441  0.55565637  0.39562827 -0.2655423
  -0.25999651  0.20580165 -0.28414693  0.15951257 -0.07003448 -0.18676741
   0.03480029 -0.24980871 -0.26831619  0.38798729 -0.42080609 -0.17862723]]


In [125]:
print(adl.intercept_)

[1.5370718]


In [126]:
adl.predict(x_test_scaled)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [127]:
np.array(y_test)

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
      dtype=int64)

In [128]:
adl.score(x_test_scaled,y_test) #score 0.7441860465116279

0.7441860465116279